### PR TITLE
Update to cursive 0.15.0

### PR DESCRIPTION
**Pull request by ColonelThirtyTwo**
Tests pass

### CODE REVIEW

**Comment by fin-ger** [comment]
Hi,

thank you for your PR. Currently @jwuensche and I are quite busy with finishing up a paper submission. It might take a couple of weeks until we get the time to look into this.

I was told there is now a `cursive-core` crate which libraries should depend on. I will have to look into that. Until then this PR will be on hold. Sorry :disappointed: 

Best regards,
Fin

**Comment by fia0** [comment]
@fin-ger The `cursive_core` crate is the one recommended to implement views exclusively, the crate is basically stripped of all the rendering stuff like `ncurses` etc. `cursive` itself is now meant to be used with applications.
I would suggest we use the transition from `cursive` `0.14` to `0.15` to change our library to fulfill this accordingly (This will also make us atleast more independent from the `cursive` crate update cycle). 
Necessary steps to achieve this require us to change our setup of tests a bit, mainly moving the tests out of `/src` to replace `cursive` with `cursive_core` in our deps. I would suggest we also use @gyscos solution here to move them to examples until we move further on migrating the tests to another method.

As already mentioned in https://github.com/deinstapel/cursive-tabs/issues/5 I would prefer to continue this with the removal of our current testing approach and replace it with `cursive::backends::puppet` to emulate a terminal.

**Comment by ColonelThirtyTwo** [comment]
If you guys want to do that, sure, sounds like a good plan. I just wanted this to work with 0.15.x. I'm sure you guys could just merge this and change the crate and testing after the fact, but I'm not going to do those parts.

**Comment by fia0** [comment]
I added some changes to your branch; from them we can continue to move the tests from.
The crate now uses `cursive_core`as it's sole dependency. I'll release the crate later today with the new tests.
In the meantime the you can use the `master` branch for `0.15`.

**Pull request merged**
